export const MOCK_ALERTS = [
  {
    id: '1',
    title: 'Fatura Cartão Black',
    amount: 3450.0,
    dueDate: new Date(Date.now() + 86400000 * 2).toISOString(),
    type: 'urgent',
    cardId: '1',
    context: 'personal',
  },
  {
    id: '2',
    title: 'Conta de Luz',
    amount: 185.4,
    dueDate: new Date(Date.now() + 86400000 * 2).toISOString(),
    type: 'urgent',
    context: 'personal',
  },
  {
    id: '3',
    title: 'Condomínio',
    amount: 850.0,
    dueDate: new Date(Date.now() + 86400000 * 5).toISOString(),
    type: 'normal',
    context: 'personal',
  },
  {
    id: '4',
    title: 'Imposto DAS',
    amount: 1250.0,
    dueDate: new Date(Date.now() + 86400000 * 4).toISOString(),
    type: 'urgent',
    context: 'business',
  },
]

export const MOCK_ASSETS = [
  {
    id: '1',
    name: 'CDB Banco Inter',
    category: 'Renda Fixa',
    value: 45000,
    rate: '110% CDI',
    context: 'personal',
  },
  {
    id: '2',
    name: 'Tesouro IPCA+ 2035',
    category: 'Tesouro Direto',
    value: 25000,
    rate: 'IPCA + 5.5%',
    context: 'personal',
  },
  {
    id: '3',
    name: 'FII HGLG11',
    category: 'FIIs',
    value: 15000,
    rate: 'Div 0.8% a.m',
    context: 'personal',
  },
  { id: '4', name: 'Ações WEGE3', category: 'Ações', value: 8500, rate: '-', context: 'personal' },
  {
    id: '5',
    name: 'Caixa Empresa',
    category: 'Renda Fixa',
    value: 35000,
    rate: '100% CDI',
    context: 'business',
  },
]

export const MOCK_ACCOUNTS = [
  {
    id: '1',
    bank: 'Nubank',
    type: 'Conta Corrente',
    balance: 12450.0,
    connected: true,
    agency: '0001',
    account: '12345-6',
    context: 'personal',
  },
  {
    id: '2',
    bank: 'Itaú',
    type: 'Conta Investimento',
    balance: 4500.0,
    connected: true,
    agency: '7890',
    account: '98765-4',
    context: 'personal',
  },
  {
    id: '3',
    bank: 'XP Investimentos',
    type: 'Corretora',
    balance: 0.0,
    connected: false,
    context: 'personal',
  },
  {
    id: '4',
    bank: 'Inter Empresas',
    type: 'Conta Corrente PJ',
    balance: 24500.0,
    connected: true,
    agency: '0001',
    account: '55555-5',
    context: 'business',
  },
]

export const MOCK_CREDIT_CARDS = [
  {
    id: '1',
    bank: 'Itaú',
    brand: 'Mastercard Black',
    lastDigits: '4321',
    totalLimit: 25000,
    availableLimit: 12450.5,
    bestPurchaseDay: 5,
    dueDate: 15,
    context: 'personal',
  },
  {
    id: '2',
    bank: 'Nubank',
    brand: 'Mastercard Platinum',
    lastDigits: '8765',
    totalLimit: 8500,
    availableLimit: 1200.0,
    bestPurchaseDay: 28,
    dueDate: 5,
    context: 'personal',
  },
  {
    id: '3',
    bank: 'Cora',
    brand: 'Visa Business',
    lastDigits: '9988',
    totalLimit: 15000,
    availableLimit: 14500.0,
    bestPurchaseDay: 10,
    dueDate: 20,
    context: 'business',
  },
]

export const MOCK_PROFILES = [
  {
    id: '1',
    name: 'Carlos (Pai)',
    role: 'Admin',
    limit: 5000,
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=4',
    context: 'personal',
    currentAge: 35,
    retirementPlanDuration: 25,
  },
  {
    id: '2',
    name: 'Marina (Mãe)',
    role: 'Admin',
    limit: 5000,
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=2',
    context: 'personal',
    currentAge: 33,
    retirementPlanDuration: 27,
  },
  {
    id: '3',
    name: 'Lucas (Filho)',
    role: 'Dependente',
    limit: 800,
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=7',
    context: 'personal',
  },
  {
    id: '4',
    name: 'João Silva',
    role: 'Edição',
    limit: 2000,
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=10',
    context: 'business',
    currentAge: 30,
    retirementPlanDuration: 35,
  },
]

export const MOCK_TRANSACTIONS = [
  {
    id: '1',
    date: new Date().toISOString().split('T')[0],
    description: 'Supermercado Extra',
    amount: -450.2,
    category: 'Alimentação > Supermercado',
    type: 'Expense',
    account: 'Nubank',
    recurrence: 'none',
    expenseType: 'variable',
    context: 'personal',
    profile: 'Carlos (Pai)',
  },
  {
    id: '2',
    date: new Date().toISOString().split('T')[0],
    description: 'Salário Carlos',
    amount: 8500.0,
    category: 'Renda > Principal',
    type: 'Revenue',
    account: 'Itaú',
    recurrence: 'monthly',
    context: 'personal',
  },
  {
    id: '3',
    date: new Date().toISOString().split('T')[0],
    description: 'Transferência Poupança',
    amount: -1500.0,
    category: 'Transferência > Interna',
    type: 'Transfer',
    account: 'Itaú',
    recurrence: 'none',
    context: 'personal',
  },
  {
    id: '4',
    date: new Date(Date.now() - 86400000 * 2).toISOString().split('T')[0],
    description: 'Pix João - Churrasco',
    amount: -120.0,
    category: 'Lazer > Eventos',
    type: 'Pix',
    account: 'Nubank',
    recurrence: 'none',
    hasAttachment: true,
    expenseType: 'variable',
    context: 'personal',
    profile: 'Marina (Mãe)',
  },
  {
    id: '5',
    date: new Date(Date.now() - 86400000 * 5).toISOString().split('T')[0],
    description: 'Fatura Itaú Black',
    amount: -3450.0,
    category: 'Outros > Cartão de Crédito',
    type: 'Expense',
    account: 'Itaú',
    cardId: '1',
    recurrence: 'none',
    expenseType: 'fixed',
    context: 'personal',
    profile: 'Carlos (Pai)',
  },
  {
    id: '6',
    date: new Date().toISOString().split('T')[0],
    description: 'Venda Consultoria',
    amount: 15000.0,
    category: 'Receita > Serviços',
    type: 'Revenue',
    account: 'Conta PJ',
    recurrence: 'none',
    context: 'business',
  },
  {
    id: '7',
    date: new Date(Date.now() - 86400000 * 3).toISOString().split('T')[0],
    description: 'Software CRM',
    amount: -450.0,
    category: 'Despesa > Ferramentas',
    type: 'Expense',
    account: 'Conta PJ',
    recurrence: 'monthly',
    expenseType: 'fixed',
    context: 'business',
    profile: 'João Silva',
  },
]

export const MOCK_CATEGORIES = {
  Alimentação: ['Supermercado', 'Delivery', 'Restaurante'],
  Moradia: ['Aluguel', 'Luz', 'Água', 'Internet'],
  Transporte: ['Combustível', 'Aplicativo', 'Manutenção'],
  Saúde: ['Farmácia', 'Plano de Saúde', 'Consultas'],
  Lazer: ['Eventos', 'Assinaturas', 'Viagens'],
  Renda: ['Principal', 'Extra', 'Dividendos'],
  Outros: ['Cartão de Crédito', 'Importado'],
}

export const MOCK_GOALS = [
  {
    id: '1',
    name: 'Reserva de Emergência',
    targetValue: 50000,
    currentValue: 32000,
    targetDate: '2025-12-01',
    monthlyDeposit: 1500,
    context: 'personal',
  },
  {
    id: '2',
    name: 'Viagem para Europa',
    targetValue: 30000,
    currentValue: 5000,
    targetDate: '2026-07-15',
    monthlyDeposit: 1000,
    context: 'personal',
  },
  {
    id: '3',
    name: 'Capital de Giro',
    targetValue: 100000,
    currentValue: 35000,
    targetDate: '2026-12-31',
    monthlyDeposit: 2000,
    context: 'business',
  },
]

export const MOCK_ACCESS_LOGS = [
  {
    id: 1,
    device: 'MacBook Pro',
    location: 'São Paulo, BR',
    ip: '192.168.1.10',
    date: '2026-03-13 09:41',
  },
  {
    id: 2,
    device: 'iPhone 13',
    location: 'São Paulo, BR',
    ip: '172.20.10.2',
    date: '2026-03-12 18:20',
  },
  {
    id: 3,
    device: 'Windows Desktop',
    location: 'Rio de Janeiro, BR',
    ip: '200.150.40.1',
    date: '2026-03-10 14:05',
  },
]

export const MOCK_TICKETS = [
  {
    id: 'TK-1042',
    user: 'carlos@familia.com',
    subject: 'Dúvida sobre simulador',
    status: 'Aberto',
    date: '2026-03-12',
  },
  {
    id: 'TK-1041',
    user: 'marina.silva@email.com',
    subject: 'Problema na sincronização Nubank',
    status: 'Em Progresso',
    date: '2026-03-11',
  },
  {
    id: 'TK-1038',
    user: 'joao.pedro@teste.com',
    subject: 'Como mudar o e-mail?',
    status: 'Resolvido',
    date: '2026-03-09',
  },
]
