export const GOAL_DELETION_PHRASES = [
  'Esta meta deixou de ser importante ou precisa de um novo plano?',
  'Pense nos seus valores de longo prazo antes de excluir.',
  'Excluir é uma escolha. O que isso revela sobre suas prioridades atuais?',
  'Metas podem ser ajustadas, não apenas abandonadas.',
  'Qual crença está por trás da decisão de desistir?',
  'O desconforto de hoje justifica o abandono de amanhã?',
  'Reavalie: é impossível ou apenas difícil no momento?',
  'Seu eu futuro agradece a reflexão de agora.',
  'Exclusão é definitiva. Arquivar preserva a possibilidade.',
  'O que você ganha e o que perde ao remover esta meta?',
  'Padrões de desistência repetidos merecem atenção.',
  'Esta decisão é impulsiva ou refletida?',
  'Metas são compassos, não prisões. Ajuste a rota.',
  'A dor do esforço ou a dor do arrependimento?',
  'Se não for agora, quando será o momento certo?',
  'Quem você se torna ao desistir deste sonho?',
  'A flexibilidade é sábia, a fuga é automática.',
  "Distinga entre 'não quero mais' e 'não consigo agora'.",
  'Seus valores mudaram ou sua paciência esgotou?',
  'Cada exclusão é uma escolha de quem você será.',
]

export const RETIREMENT_WITHDRAWAL_PHRASES = [
  'Seu eu de 65 anos está confiando nesta decisão de hoje.',
  'O conforto de agora pode ser o sacrifício de amanhã.',
  'Reavalie: é necessidade real ou desejo imediato?',
  'Aposentadoria é não-negociável. Encontre outra fonte.',
  'O tempo não volta, mas o dinheiro aposentado sim.',
  'Esta retirada é exceção ou está se tornando regra?',
  'Pense no efeito dominó desta escolha em 20 anos.',
  'Segurança futura versus prazer presente: qual pesa mais?',
  'Seu eu futuro não poderá cobrar esta dívida.',
  'Há alternativas menos prejudiciais ao seu amanhã?',
  'A dor da disciplina ou a dor da dependência?',
  'Este valor é para sobreviver ou para satisfazer?',
  'Aposentadoria é promessa para o futuro você.',
  'Quebrar promessas consigo mesmo gera padrões.',
  'Reflita: esta urgência é real ou fabricada?',
  'O dinheiro aposentado trabalha enquanto você dorme.',
  'Sacrificar o futuro pelo presente é jogo perdido.',
  'Seu eu idoso agradece cada real preservado.',
  'Esta retirada é investimento ou prejuízo disfarçado?',
  'Proteja quem você será, não apenas quem é.',
]

export const EMERGENCY_WITHDRAWAL_PHRASES = [
  'Emergências não avisam. Esta retirada é inevitável?',
  'A reserva existe para ser usada, não para ser gasta.',
  'Distinga emergência real de urgência emocional.',
  'Seu colchão de segurança está sendo furado?',
  'Reabastecer será possível? Quando? Como?',
  'O medo de hoje justifica a vulnerabilidade de amanhã?',
  'Esta retirada é sobrevivência ou conforto?',
  'A reserva é para imprevistos, não para desejos.',
  'Quanto tempo levará para reconstruir este valor?',
  'Sem colchão, qualquer queda é fatal.',
  'Esta decisão é reativa ou proativa?',
  'A ansiedade de agora não deve ditir o amanhã.',
  'Há outras fontes antes de tocar a reserva?',
  'Sua segurança financeira está sendo negociada?',
  'A reserva é último recurso, não primeiro.',
  'Reflita: este gasto é inevitável ou evitável?',
  'Cada real retirado é um passo mais perto da borda.',
  'Proteja seu futuro imediato com sabedoria.',
  'A reserva reconstruída é mais difícil que a primeira.',
  'Use com consciência, reconstrua com prioridade.',
]

export const ADD_GOAL_PHRASES = [
  'Novo sonho, novo compromisso. Seu eu futuro agradece.',
  'Cada meta adicionada é um passo em direção a quem você quer ser.',
  'Aposentadoria fortalecida: presente para o futuro você.',
  'Sonhos claros geram ações claras. Parabéns pelo novo alvo.',
  'Seu eu de amanhã já celebra esta decisão de hoje.',
  'Mais um degrau na construção da sua liberdade.',
  'Metas nascem de valores. Valide este novo propósito.',
  'Aposentadoria é amor próprio diferido. Continue.',
  'Sonhos grandes exigem passos consistentes. Começou.',
  'Cada aporte é voto de confiança no seu potencial.',
  'Novo capítulo, novas possibilidades. Mãos à obra.',
  'Seu futuro está sendo escrito agora. Boa escolha.',
  'A disciplina de hoje constrói o conforto de amanhã.',
  'Metas são promessas que você faz a si mesmo.',
  'Aposentadoria: segurança que você mesmo constrói.',
  'Sonhos sem ação são ilusões. Você está agindo.',
  'Cada real guardado é liberdade comprada antecipadamente.',
  'Novo alvo, novo foco. Mantenha a mira.',
  'Seu eu futuro está assistindo e agradecendo.',
  'Construir sonhos é ato de coragem e esperança.',
]

export const HIGH_VALUE_PHRASES = [
  'Este gasto representa quanto da sua renda? Vale a pena?',
  'Alto valor, alto impacto. Reflita antes de confirmar.',
  'Seu orçamento está sendo comprometido severamente.',
  'Esta decisão é consciente ou impulsiva?',
  'O prazer desta compra supera o estresse do aperto?',
  'Você está negociando necessidades básicas por desejos?',
  'Alto valor exige alta certeza. Tem certeza?',
  'Este gasto é investimento ou prejuízo emocional?',
  'Sua reserva de emergência está sendo ameaçada?',
  'Reflita: é prioridade real ou urgência fabricada?',
  'O peso deste valor será sentido por quanto tempo?',
  'Você está comprando algo ou comprando uma sensação?',
  'Alto valor próximo da renda é risco calculado ou azar?',
  'Esta escolha alinha com seus valores de longo prazo?',
  'O remorso deste gasto durará mais que o prazer?',
  'Sua segurança financeira está sendo trocada por quê?',
  'Reavalie: há alternativas menos onerosas?',
  'Cada real acima do confortável é decisão de risco.',
  'Este gasto é necessidade, desejo ou fuga emocional?',
  'Proteja seu equilíbrio. Alto valor exige alta reflexão.',
]

export function getRandomPhrase(phrases: string[]): string {
  return phrases[Math.floor(Math.random() * phrases.length)]
}
